version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: muka-backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: unless-stopped